server:
  port: 80
binlog:
  name: Bincker的个人博客
  copy-right: copyright © 2021 Bincker
  icp: 京ICP备1234567890号
  github: https://github.com/Bincker1973
  base-path: /api
  datetime-format: yyyy-MM-dd HH:mm:ss
  date-format: yyyy-MM-dd
  time-format: HH:mm:ss
  verify-code:
    image-path: ./verify-images
  files:
    type: local
    allow-referer:
      - "*"
    allow-empty-referer: false
    location: upload-file
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&serverTime=Asia/Shanghai&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    serialization:
      WRITE_ENUMS_USING_TO_STRING: true
    time-zone: Asia/Shanghai
  profiles:
    active: @profiles.active@
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 24MB
  web:
    locale: zh_CN
    resources:
      cache:
        period: 2592000
